pipeline {
  
   environment {
     DOCKER_REGISTRY='https://hub.docker.com/'
     CONTAINER='kiranp23/apache'
     VERSION="1.${BUILD_NUMBER}"
   }

   agent any
     
    stages {
     
     stage('build docker image') {
         steps {
           script {
             docker.withRegistry("${DOCKER_REGISTRY}", 'docker-id') {
                def img = docker.build("${CONTAINER}:${VERSION}")
                img.push()
             }
           }
         }
     }

     stage('Check the staus') {
         steps {
           sh 'ansible-playbook ${WORKSPACE}/prodserver/image-status.yml'
         }
     }
    
     stage('Copy SSH key to dev server') {
         steps {
           sh 'ansible-playbook -i ${WORKSPACE}/prodserver/jenkinsci --private-key /sites/privatekey.pem ${WORKSPACE}/prodserver/push-ssh-key.yml'
         }
     } 
 
     stage('Deploy on dev server') {
        steps {
         withCredentials([
             usernamePassword(
                credentialsId: 'docker-id',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASSWORD'
             )
           ])
           {
            script {
             echo "deploying to dev server"
             sh 'ansible-playbook -i ${WORKSPACE}/prodserver/jenkinsci ${WORKSPACE}/prodserver/deploy-dev.yml -e "hub_user=${DOCKER_USER} hub_pass=${DOCKER_PASSWORD} ${VERSION} ansible_python_interpreter=/usr/bin/python2.7"'
            }
           }
        }
     }
   }
}
