pipeline {

   environment {
     registryCredential = 'docker_id'
   }

   agent any
     
    stages {
     
     stage('build docker image') {
         steps {
          sh 'sudo docker build -t apache ${WORKSPACE}/devserver'
         }
     }

     stage('Check the staus') {
         steps {
           sh 'ansible-playbook ${WORKSPACE}/devserver/image-status.yml'
         }
     }
    
     stage('Copy SSH key to dev server') {
         steps {
           sh 'ansible-playbook -i ${WORKSPACE}/devserver/jenkinsci --private-key /sites/privatekey.pem ${WORKSPACE}/devserver/push-ssh-key.yml'
         }
     } 
 
     stage('Copy html file in to dev server') {
         steps {
           sh 'ansible-playbook -i ${WORKSPACE}/devserver/jenkinsci ${WORKSPACE}/devserver/push-to-dev.yml'
         }
     }
  
     stage('Run health check on dev server') {
        steps {
           sh 'ansible-playbook -i ${WORKSPACE}/devserver/jenkinsci ${WORKSPACE}/devserver/health-check.yml'
        }
     }
   }
}
