pipeline {
   agent any
     
    stages {
     
     stage('build docker image') {
         steps {
          sh 'sudo docker build -t apache ${WORKSPACE}/devserver'
         }
     }

     stage('Check the staus') {
         steps {
           sh 'ansible-playbook ${WORKSPACE}/image-status.yml -e "hub_user=${HUB_user} hub_pass=${HUB_pass}"'
         }
     }
    
     stage('Copy SSH key to dev server') {
         steps {
           sh 'ansible-playbook -i ${WORKSPACE}/jenkinsci --private-key /sites/privatekey.pem ${WORKSPACE}/push-ssh-key.yml'
         }
     } 
 
     stage('Copy html file in to dev server') {
         steps {
           sh 'ansible-playbook -i ${WORKSPACE}/jenkinsci ${WORKSPACE}/push-to-dev.yml'
         }
     }
  
     stage('Run health check on dev server') {
        steps {
           sh 'ansible-playbook -i ${WORKSPACE}/jenkinsci ${WORKSPACE}/health-check.yml "hub_user=${HUB_user} hub_pass=${HUB_pass}"'
        }
     }
   }
}
